<?php
include_once '../../../controllers/auth/checkSession.php';
include_once '../../../../application/configs/conection.php';
include_once "../../../controllers/user/listuser.php";
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">

    <title>Usuários</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../../../assets/_css/admin.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/application/views/admin/admin.phtml">CadUsu</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sair</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item active">
                        <a class="nav-link" href="/application/views/admin/user/listuser.phtml">
                            <span data-feather="bar-chart-2"></span>
                            Usuários
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>
                </ul>

            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Usuários</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                        <button class="btn btn-sm btn-outline-dark"><a href="/application/views/admin/user/register.phtml">Adicionar</a></button>
                    </div>
                </div>
            </div>


            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Telefone</th>
                        <th>Status</th>
                        <th>Nivel de acesso</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php while ($date = pg_fetch_assoc($sql1)) {  ?>
                        <tr>
                            <th scope="row"><?php echo $date['member_id'];?></th>
                            <td>
                                <?php echo $date['nome']; ?>
                            </td>
                            <td>
                                <?php echo $date['email']; ?>
                            </td>

                            <td>
                                <?php echo $date['tel_cel']; ?>
                            </td>

                            <td>
                                <?php echo $date['ds_status']; ?>
                            </td>

                            <td>
                                <?php echo $date['ds_nome_level']; ?>
                            </td>
                            <td>
                                <?php if($date['ds_status'] !== "Excluído") : ?>
                                    <a href="/application/controllers/user/viewUser.php?acao=view&id=<?php echo $date['member_id'];?>">
                                        <button title="Visualizar usuário">
                                            <i class="material-icons">search</i>
                                        </button>
                                    </a>
                                    <a href="/application/controllers/user/manteruser.php?acao=excluir&id=<?php echo $date['member_id'];?>">
                                        <button title="Excluir usuário">
                                            <i class="material-icons">close</i>
                                        </button>
                                    </a>
                                    <a href="/application/controllers/user/manteruser.php?acao=editar&id=<?php echo $date['member_id'];?>">
                                        <button title="Editar usuário">
                                            <i class="material-icons">edit</i>
                                        </button>
                                    </a>
                                <?php else:?>
                                    <a href="/application/controllers/user/manteruser.php?acao=view&id=<?php echo $date['member_id'];?>">
                                        <button title="Visualizar usuário">
                                            <i class="material-icons">search</i>
                                        </button>
                                    </a>
                                <?php endif;?>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </main>
    </div>
</div>

<script type="text/javascript" src="../../../assets/_js/jquery-3.2.1.min.js"></script>
<script src="../../../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
</body>
</html>