<?php
include_once '../../../../application/controllers/auth/checkSession.php';
include_once '../../../../application/configs/conection.php';
include_once "../../../../application/controllers/user/listuser.php";
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../../../assets/_css/admin.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/application/views/admin/admin.phtml">CadUsu</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sair</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="/application/views/admin/user/listuser.phtml">
                            <span data-feather="bar-chart-2"></span>
                            Usuários
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Integrations
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Usuários - <small>adicionar</small></h1>
            </div>

            <form method="post" id="form_contato" action="/application/controllers/cadastrar.php" class="form">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="cpf">Cpf:</label>
                        <input type="text" class="form-control" id="cpf" placeholder="cpf">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="nome">Nome:</label>
                        <input type="text" class="form-control" id="nome" placeholder="Nome">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" placeholder="Email">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputPassword4">Password:</label>
                        <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
                    </div>
                </div>
                <div class="form-group">
                    <label for="tel">Telefone Celular:</label>
                    <input type="text" class="form-control" id="tel" placeholder="Telefone Celular">
                </div>
                <div class="form-group">
                    <label for="aniver">Data de Aniversário:</label>
                    <input type="text" class="form-control" id="aniver" placeholder="Data de Aniversário">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>
            </form>
        </main>
    </div>
</div>


<script type="text/javascript" src="../../../../assets/_js/jquery-3.2.1.min.js"></script>
<script src="../../../../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
</body>
</html>