<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Teste CSS e HTML</title>
    <link rel="stylesheet" href="../../../assets/_css/cadastroelogin.css">
    <script type="text/javascript" src="../../../assets/_js/jquery-3.2.1.min.js"></script>


</head>
<body>
<div id="inteface">
    <header>
        <div>
            <img id="icone" src="../../../assets/imagens/guitar.png"/>
        </div>
        <h1 id="h1-cad">Cadastro de novos Membros</h1>
    </header>
<form method="post" id="form_contato" action="/application/controllers/cadastrar.php" class="form">
    <fieldset id="usuario"><legend><strong>Indentificão do Usuário</strong></legend>
        <table>
        <tr class="form-group">
            <td>
                <label for="cpf" class="label">
                    CPF:
                </label>
            </td>
            <td>
                <input type="text" class="input " name="cpf" id="cpf" required>
            </td>
        </tr>
        <tr class="form-group">
            <td>
                <label for="nome" class="label">
                    Nome:
                </label>
            </td>
            <td>
                <input type="text" class="input " name="nome" id="nome" required>
            </td>
        </tr>
        <tr class="form-group">
            <td>
                <label for="email" class="label">
                    Email:
                </label>
            </td>
            <td>
               <input type="email" class="input " name="email" id="email" required>
            </td>
        </tr>
        <tr class="form-group">
            <td>
                <label for="senha" class="label">
                    Senha:
                </label class="label">
            </td>
            <td>
                <input type="password" class="input " name="senha" id="senha"  maxlength="48" required>
            </td>
        </tr>
        <tr class="form-group">
            <td>
                <label for="Rsenha" class="label">
                   Redigite a Senha:
                </label class="label">
            </td>
            <td>
                <input type="password" class="input " name="Rsenha" id="Rsenha"  maxlength="48" required>
            </td>
        </tr>
        <tr class="form-group">
            <td>
                <label for="tel" class="label">
                    Tel. Celular:
                </label>
            </td>
            <td>
                <input type="text" name="tel" class="input " id="tel" required>
            </td>
        </tr>
        <tr class="form-group">
            <td>
                <label for="data" id="label-data" class="label">
                    Data de Aniversário:
                </label>
            </td>
            <td>
                <input type="text" class="input " name="data" id="data" data-validation="birthdate" required>
            </td>
        </tr>

        </table>
        <div>
            <input type="submit" id="btn" value="cadastrar" onsubmit="" class="btn btn-primary" >
        </div>
    </fieldset>
</form>
<!--    <div>-->
<!--        <a href="login.phtml"><input type="submit" id="btn" value="Fazer login"  class="btn" ></a>-->
<!--    </div>-->
</div>

</body>
    <script type="text/javascript" src="../../../assets/_js/jquery.mask.min.js"></script>
    <script type="text/javascript" src="../../../assets/_js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="../../../assets/_js/form.js"></script>
</html>
