<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teste CSS e HTML</title>
    <link rel="stylesheet" href="../../../assets/_css/cadastroelogin.css">
    <link rel="stylesheet" href="../../../assets/_css/bootstrap.min.css">

</head>
<body>
<div id="inteface">
    <header>
        <div>
            <img id="icone" src="../../../assets/imagens/guitar.png"/>
        </div>
        <h1>Login dos Membros</h1>
    </header>

    <form method="post" action="/application/controllers/verifica_login.php">
        <fieldset id="usuario"><legend><strong>Dados para acesso</strong></legend>
            <table id="table">
                <tr>
                    <td>
                        <label for="cpf" class="label">
                            Cpf:
                        </label>
                    </td>
                    <td>
                        <input type="text" class="form-control form-control-sm" name="cpf" id="cpf" maxlength="11">
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="senha" class="label">
                            Senha:
                        </label>
                    </td>
                    <td><input type="password" class="form-control  form-control-sm" name="senha" id="senha" maxlength="48" ></td>
                </tr>
            </table>
        </fieldset
                <div>
                    <input type="submit" value="Efetuar Login" class="btn btn-primary">
                </div>
    </form>
<!--        <div>-->
<!--            <a href="cadastro.phtml"><input type="submit" value="Fazer cadastro"  class="btn btn-primary" ></a>-->
<!--        </div>-->
</div>

</body>

<script type="text/javascript" src="../../../assets/_js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="../../../assets/_js/jquery.mask.min.js"></script>
<script type="text/javascript" src="../../../assets/_js/jquery.validate.min.js"></script>
<script type="text/javascript" src="../../../assets/_js/form.js"></script>
<script type="text/javascript" src="../../../assets/_js/bootstrap.min.js"></script>

</html>