<?php
$nivel_necessario = 2;
include '../../controllers/verifica_sessao.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album</title>
    <link rel="stylesheet" href="../../../assets/_css/album.css">

</head>
<body>
<div id="inteface">
    <header>
        <nav id="menu">
            <ul type="disc">
                <li onmouseover="mudaFoto('../../../assets/imagens/casa.png')" onmouseout="mudaFoto
             ('../../../assets/imagens/camera.png')">
                    <a href="cssehtml.phtml">
                        home
                    </a>
                </li>

                <li onmouseover="mudaFoto('../../../assets/imagens/camera.png')" onmouseout="mudaFoto
             ('../../../assets/imagens/camera.png')">
                    <a href="allbum.phtml">
                        Album de Fotos
                    </a>
                </li>

                <li onmouseover="mudaFoto('../../../assets/imagens/media.png')" onmouseout="mudaFoto
             ('../../../assets/imagens/camera.png')">
                    <a href="media.phtml">
                        Multimedia
                    </a>
                </li>
                <li onmouseover="mudaFoto('../../../assets/imagens/media.png').style.transition='opacity 1s'" onmouseout="mudaFoto
                ('../../../assets/imagens/media.png')">
                    <a href="listuser.phtml">
                        Dados dos Usuários
                    </a>
                </li>

            </ul>
                <div id="bemvindo">
                    <a href="" style="font-size: 17px">
                        Seja Bem-vindo, <b><?php echo "{$_SESSION['nome']}";?></b>
                    </a>

                    <a <?php echo "<a href=\"../../controllers/logout.php\"><img id=\"exit\" src=\"../../../assets/imagens/exit.png\" width=\"25\" height=\"25\" title=\"Sair do Sistema\"></a>";?>
                    </a>
                </div>
        </nav>
        <div>
            <img id="icone" src="../../../assets/imagens/media.png"/>
        </div>

    </header>
    <hr style="height:2px; border:none; color:#5c5c5c; background-color:#7f7f7f; margin-top: 0px; margin-bottom: 0px;">
<ul id="galeria" class="zoom">
    <li id="ft1"><span>foto1</span></li>
    <li id="ft2"><span>foto2</span></li>
    <li id="ft3"><span>foto3</span></li>
    <li id="ft4"><span>foto4</span></li>
    <li id="ft5"><span>foto5</span></li>
    <li id="ft6"><span>foto6</span></li>
</ul>

</div>

</body>
<script src="../../../assets/_js/geraljs.js"></script>
</html>