<?php
$nivel_necessario = 1;
include '../../controllers/verifica_sessao.php';
include('../../configs/conection.php');
include "../../controllers/viewuser.php";
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Teste CSS e HTML</title>
    <link rel="stylesheet" href="../../../assets/_css/dadosuser.css">
    <link rel="stylesheet" href="../../../assets/_css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <script type="text/javascript" src="../../../assets/_js/jquery-3.2.1.min.js"></script>

</head>
<body>
<div id="inteface">
    <header>
        <a href="cssehtml.phtml">Voltar para pagina principal</a>
        <div>
            <img id="icone" src="../../../assets/imagens/guitar.png"/>
        </div>
        <h1 id="h1-cad">Dados dos Membros</h1>
    </header>
    <br>
    <br>
    <br>
        <table class="table">
            <thead>
            <tr>
                <th>id</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Status</th>
                <th>Nivel de acesso</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php while (pg_fetch_assoc($sql1)) {  ?>
            <tr>
                <th scope="row"><?php echo $date['member_id'];?></th>
                <td>
                    <?php echo $date['nome']; ?>
                </td>
                <td>
                    <?php echo $date['email']; ?>
                </td>

                <td>
                    <?php echo $date['tel_cel']; ?>
                </td>

                <td>
                    <?php echo $date['ds_status']; ?>
                </td>

                <td>
                    <?php echo $date['ds_nome_level']; ?>
                </td>
                <td>
                    <a title="Excluir usuário" href="/application/controllers/viewuser.php?acao=excluir&id='<?php echo $date['member_id'];?>'">Excluir</a>
                </td>
            </tr>
            <?php } ?>
            </tbody>
        </table>
</div>

</body>
<script type="text/javascript" src="../../../assets/_js/jquery.mask.min.js"></script>
<script type="text/javascript" src="../../../assets/_js/jquery.validate.min.js"></script>
<script type="text/javascript" src="../../../assets/_js/form.js"></script>
</html>


