<?php
$nivel_necessario = 1;
include_once '../../controllers/verifica_sessao.php';
include_once '../../configs/conection.php';
include_once "../../controllers/listuser.php";
?>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Teste CSS e HTML</title>
    <link rel="stylesheet" href="../../../assets/_css/dadosuser.css">
    <link rel="stylesheet" href="../../../assets/_css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <script type="text/javascript" src="../../../assets/_js/jquery-3.2.1.min.js"></script>

</head>
<body>
<div id="inteface">
    <header>

        <div>
            <img id="icone" src="../../../assets/imagens/guitar.png"/>
        </div>
        <h1 id="h1-cad">Dados dos Membros</h1>
    </header>
    <br>
    <br>
    <br>
        <table class="table">
            <thead>
            <tr>
                <th>id</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Status</th>
                <th>Nivel de acesso</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php while ($date = pg_fetch_assoc($sql1)) {  ?>
            <tr>
                <th scope="row"><?php echo $date['member_id'];?></th>
                <td>
                    <?php echo $date['nome']; ?>
                </td>
                <td>
                    <?php echo $date['email']; ?>
                </td>

                <td>
                    <?php echo $date['tel_cel']; ?>
                </td>

                <td>
                    <?php echo $date['ds_status']; ?>
                </td>

                <td>
                    <?php echo $date['ds_nome_level']; ?>
                </td>
                <td>
                    <?php if($date['ds_status'] !== "excluído") : ?>
                    <a href="/application/controllers/manteruser.php?acao=view&id=<?php echo $date['member_id'];?>">
                        <button title="Visualizar usuário">
                            <i class="material-icons">search</i>
                        </button>
                    </a>

                    <a href="/application/controllers/manteruser.php?acao=excluir&id=<?php echo $date['member_id'];?>">
                        <button title="Excluir usuário">
                            <i class="material-icons">close</i>
                        </button>
                    </a>
                    <a href="/application/controllers/manteruser.php?acao=editar&id=<?php echo $date['member_id'];?>">
                        <button title="Editar usuário">
                            <i class="material-icons">edit</i>
                        </button>
                    </a>
                    <?php else:?>
                    <a href="/application/controllers/manteruser.php?acao=view&id=<?php echo $date['member_id'];?>">
                        <button title="Visualizar usuário">
                            <i class="material-icons">search</i>
                        </button>
                    </a>
                    <?php endif;?>
                </td>
            </tr>
            <?php } ?>
            </tbody>
        </table>
</div>

</body>
<script type="text/javascript" src="../../../assets/_js/jquery.mask.min.js"></script>
<script type="text/javascript" src="../../../assets/_js/jquery.validate.min.js"></script>
<script type="text/javascript" src="../../../assets/_js/form.js"></script>
</html>


